# Generated by Django 5.2 on 2025-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('feedback', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
